### ISSUE TITLE
Feedback [Week 2]

### ISSUE THREAD

**Issue by khattakdev** [varsharathore16/MLH-Project-2#44]
Hey Fellows 👋

## .vscode
Please ensure that `.vscode` is uploaded on purpose and intentionally. It's not bad to commit this folder but only when you know what you're doing.

## GitHub Actions
I noticed most of the pull requests didn't pass the GitHub actions test and still merged. Try not to do this, it's a bad practice. If something is failing, try fixing that first then continue working on the rest of the part.

## Commented out code
I noticed some commented out code, this too is a bad practice. Try to remove all such code when refactoring.
![image](https://user-images.githubusercontent.com/37709578/129487515-ca96f691-fae2-4d02-b2eb-50b114ea3ef7.png)
~ _backend/app.py_

- [x] Fix the failing GitHub Actions
- [x] Refactor the Code
- [x] Write some tests
- [x] Improve the UI
- [x] Make a demo Video

Remember, this week is to finalize everything and to ensure everything is working correctly. So please make sure you focus on the current codebase rather than introducing new features.

**Note:** You folks need to speed up a little bit.

@cccswann @Lanc33llis @varsharathore16 @stcwang

**Comment by varshar4** [comment]
just refactored code - 8/16/2021
- removed commented out code
- deleted .vscode directory

**Comment by varshar4** [comment]
@cccswann had updated the lint.yml file for passing the tests earlier today - 8/16/2021

**Comment by ciciswann** [comment]
Wrote initial unit tests PR #59. Will be adding more as time permits.

**Comment by varshar4** [comment]
All tasks completed as of 8/19/2021 - demo vid will be on youtube shortly and therefore on devpost too
