### ISSUE TITLE
[Week 1] Feedback

### ISSUE THREAD

**Issue by khattakdev** [varsharathore16/MLH-Project-2#8]
Hey Fellows 👋,

Apologies for being this much lately but you know the reason.
Here is feedback for the previous week (week 1)

## GitHub Best Practices
I see there isn't very good usage of GitHub best practices. There are few pull requests but there are no issues created. I know you folks are using Notion but sticking to GitHub is a good idea as it makes everything visible to everyone and also the GitHub issues work very well with the Pull Request feature. 

## Project Structure
Generally, the folder layout looks good, I can see `backend`, `frontend` folders which make things pretty obvious but I think there is still room for improvement. There is a nested folder `project` in the `frontend` folder, which is confusing. You can just have `frontend` and have all the files in it directly rather than having another folder (`project`). 

## Readme
The readme looks good, has `installation` step but there isn't any description. Having a proper description will complete the readme. You can add information like what the project is about, what does it do, etc.

## Project Name
The project's name is `MLH-Project-2`. Maybe you folks can think of a better name for the project and change it.

@cccswann @Lanc33llis @varsharathore16 @stcwang

**Comment by varshar4** [comment]
Thanks Arsalan!
